### ISSUE TITLE
Editing dod.ctd documentation 

### ISSUE THREAD

**Issue by AnnieHow** [AnnieHow/dod#21]
@dankelley suggested we edit `dod.ctd` documentation before doing other documentation. 

I edited it this morning in commit 1d58872cea802ae65ac7586424e450c3208e8ee0. Opening this for comments on changes before going into other function roxygen and vignettes!

**Comment by dankelley** [comment]
Thanks!  A few possibilities for changes:

* [ ] debug=1 also leads to debugging, so the doc on that should be altered.
* [ ] I think all our functions will have a `debug` argument.  For this reason, I suggest using roxygen templates.  This is documented in Hadley's book, and you can see examples in oce (look in the `man-roxygen` directory for something with `debug` in the name, and then look in most any `R/*R` file to see that we don't use `@param` for debug, but another syntax instead).  The beauty of using templates is that then if we change the wording, we don't have to edit in a lot of places.
* [ ] we ought to have a template for `destdir` also
* [ ] I am guessing that the `program` might grow to have maybe 10 possibilities, and it will get tricky documenting them (and the `ID` and `index` possibilities) all.  I would be inclined to say `see \sQuote{Details}` in the doc for these things, and in the Details section, to put a table with a col for program, another for the pattern for ID, and a third that is yes/no for whether index works.

I think it's great that we are working on one particular function to start, because we can play with wording and organization to find something that feels "right" and then writing docs for the others becomes easy.

**Comment by AnnieHow** [comment]
@dankelley by pattern for ID do you mean the following information currently under the ID argument;

"For BBMP, this is the desired file from the index. For BATS, is the 5 digit cruise ID."

**Comment by AnnieHow** [comment]
A table in the Details section was added in commit 7df05bec06ae436708ffdc1b8eb143f036fc9cb2.

**Comment by AnnieHow** [comment]
debug template made in commit d73fb109192894dd95b66512c9a63b523d30ca04.

**Comment by AnnieHow** [comment]
destdir template added in commit d24954b233e40e955180dc6d9189b4828fce25cc.

**Comment by AnnieHow** [comment]
@dankelley comments have been addressed. Open to any other modifications! @j-harbin if you see anything too over the next week let me know!
